apiVersion: v1
kind: Service
metadata:
  name: linkedin-caption-webapp-service
  labels:
    app: linkedin-caption-webapp
spec:
  type: NodePort  # Required by assignment - exposes service on static port
  selector:
    app: linkedin-caption-webapp
  ports:
  - port: 3000          # Service port
    targetPort: 3000     # Container port
    nodePort: 30080      # External access port (range: 30000-32767)
    protocol: TCP
    name: http
  sessionAffinity: None
